/* fxtls CH-probe: connect to host:port and send exactly one Firefox-152
 * ClientHello (generated by real NSS) for fingerprint verification. */
#include <stdio.h>
#include <stdlib.h>
#include <prinit.h>
#include <prio.h>
#include <prnetdb.h>
#include <prerror.h>
#include <nss.h>
#include <ssl.h>
#include "fxtls_config.h"

int main(int argc, char **argv) {
    int port     = argc > 2 ? atoi(argv[2]) : 8443;
    int ech_size = argc > 3 ? atoi(argv[3]) : 100;

    PR_Init(PR_USER_THREAD, PR_PRIORITY_NORMAL, 0);
    if (NSS_NoDB_Init(".") != SECSuccess) { fprintf(stderr, "NSS init failed\n"); return 1; }
    NSS_SetDomesticPolicy();

    PRNetAddr addr;
    PR_InitializeNetAddr(PR_IpAddrLoopback, (PRUint16)port, &addr);
    PRFileDesc *tcp = PR_OpenTCPSocket(PR_AF_INET);
    if (PR_Connect(tcp, &addr, PR_SecondsToInterval(5)) != PR_SUCCESS) {
        fprintf(stderr, "connect failed: %d\n", PR_GetError()); return 1;
    }
    PRFileDesc *fd = SSL_ImportFD(NULL, tcp);
    fxtls_configure(fd, ech_size);
    SSL_SetURL(fd, "localhost");
    SSL_ResetHandshake(fd, PR_FALSE);
    SSL_ForceHandshake(fd);            /* sends ClientHello; sink closes -> expected error */

    PR_Close(fd);
    NSS_Shutdown();
    PR_Cleanup();
    return 0;
}
